### Autograd
- It is the pytorch automatic differentiation engine that powers neural network traning.


#### Importing libraries
- torch

In [1]:
import torch

#### Two tensors
- for example we have two tensors a and b.

In [3]:
a=torch.tensor([5.],requires_grad=True)
b=torch.tensor([6.],requires_grad=True)

In [4]:
a

tensor([5.], requires_grad=True)

In [5]:
b

tensor([6.], requires_grad=True)

#### Define y
- grad_fn=<SubBackward0> function associated with y
- Let's say "y" is the loss. 

In [6]:
y=a**3-b**2

In [7]:
y # lets y is an error or loss

tensor([89.], grad_fn=<SubBackward0>)

#### calculate gradiance using pytorch
- we will calculate
- dy/da=3*a**2=75
- dy/db=-2b=-12

In [9]:
print(a.grad)
print(b.grad)

None


#### Backpropagate
- Backpropagate this error through the network.

In [10]:
y.backward()

#### calculate gradiance
- we calculate the above step using grad function automatically.

In [11]:
a.grad

tensor([75.])

In [12]:
b.grad

tensor([-12.])

#### Define weight and bais
- w is weight 
- b is bais

In [13]:
w=torch.rand(10,1,requires_grad=True)
b=torch.rand(1,requires_grad=True)

In [14]:
w

tensor([[0.7162],
        [0.4765],
        [0.7713],
        [0.6660],
        [0.0801],
        [0.2549],
        [0.8759],
        [0.3716],
        [0.4178],
        [0.7435]], requires_grad=True)

In [ ]:
b

#### Featues
- one sample

In [16]:
x=torch.rand(1,10)

In [17]:
x

tensor([[0.6609, 0.6915, 0.9395, 0.4689, 0.6861, 0.9159, 0.6258, 0.4448, 0.1200,
         0.0871]])

- Perform linear regression

In [19]:
output=torch.matmul(x,w)+b

In [22]:
output

tensor([[3.1667]], grad_fn=<AddBackward0>)

- Calculate loss

In [20]:
loss=1-output

In [21]:
loss

tensor([[-2.1667]], grad_fn=<RsubBackward1>)

In [23]:
loss.backward()

In [24]:
w.grad

tensor([[-0.6609],
        [-0.6915],
        [-0.9395],
        [-0.4689],
        [-0.6861],
        [-0.9159],
        [-0.6258],
        [-0.4448],
        [-0.1200],
        [-0.0871]])

#### Update the weights
- Here we don't want to calulate the gradient we need to updates the weights. 

In [26]:
with torch.no_grad(): # sets the required grad to false
    w=w-0.001 * w.grad.data #0.001 is the loearning rate.

In [27]:
w

tensor([[0.7169],
        [0.4772],
        [0.7722],
        [0.6664],
        [0.0808],
        [0.2558],
        [0.8765],
        [0.3720],
        [0.4179],
        [0.7436]])

- In every iteration we need to update the weigths which is done by using optimizers 