#### Importing Libraries
- torch
- numpy

In [54]:
import torch 
import numpy as np

- Checking for cuda

In [55]:
torch.cuda.is_available()

True

- Check GPU

In [56]:
!nvidia-smi

Tue Jun 15 19:25:37 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 452.56       Driver Version: 452.56       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce MX350      WDDM  | 00000000:30:00.0 Off |                  N/A |
| N/A   46C    P8    N/A /  N/A |    467MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#### Create list
- list of list

In [57]:
some_data=[[1,2],[3,4]]

In [58]:
some_data

[[1, 2], [3, 4]]

#### Check type 
- list

In [59]:
type(some_data)

list

#### Create or convert to numpy arrray
- np.array
- asarray
- both gives same result

In [60]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [61]:
np.asarray(some_data)

array([[1, 2],
       [3, 4]])

#### Convert to tensor
- from numpy array to tensor

In [62]:
some_data=torch.tensor(some_data)

#### check type of array
- torch.Tensor

In [63]:
type(some_data)

torch.Tensor

#### check data type of array
- torch.int64

In [64]:
some_data.dtype

torch.int64

#### Generate random array

In [65]:
#  numpy array to torch
numpy_array=np.random.rand(3,4)

In [66]:
numpy_array

array([[0.77438552, 0.85337217, 0.38099638, 0.63218279],
       [0.00210916, 0.21594631, 0.28296344, 0.15746233],
       [0.90241125, 0.68210277, 0.32532491, 0.09033522]])

#### Convert array to torch
- no_from
- from_numpy

In [67]:
torch.from_numpy(numpy_array)

tensor([[0.7744, 0.8534, 0.3810, 0.6322],
        [0.0021, 0.2159, 0.2830, 0.1575],
        [0.9024, 0.6821, 0.3253, 0.0903]], dtype=torch.float64)

- Converting to tensors 

In [68]:
torch.tensor(numpy_array)

tensor([[0.7744, 0.8534, 0.3810, 0.6322],
        [0.0021, 0.2159, 0.2830, 0.1575],
        [0.9024, 0.6821, 0.3253, 0.0903]], dtype=torch.float64)

#### Generate tensord of ones
- torch.ones


In [69]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

- torch.ones

In [70]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#### Generate tensord randomly
- torch.rand

In [71]:
my_tensor=torch.rand(3,4)

In [72]:
my_tensor

tensor([[0.1145, 0.6827, 0.3909, 0.7687],
        [0.8610, 0.6682, 0.7992, 0.3501],
        [0.2820, 0.1723, 0.9610, 0.1428]])

#### Data type of tensor

In [73]:
my_tensor.dtype

torch.float32

#### Check tensor on which device
- CPU

In [74]:
my_tensor.device

device(type='cpu')

#### Store tensor to GPU

In [75]:
my_tensor.to("cuda")

tensor([[0.1145, 0.6827, 0.3909, 0.7687],
        [0.8610, 0.6682, 0.7992, 0.3501],
        [0.2820, 0.1723, 0.9610, 0.1428]], device='cuda:0')

In [76]:
#inplace
my_tensor=my_tensor.to("cuda")

In [77]:
my_tensor

tensor([[0.1145, 0.6827, 0.3909, 0.7687],
        [0.8610, 0.6682, 0.7992, 0.3501],
        [0.2820, 0.1723, 0.9610, 0.1428]], device='cuda:0')

#### Indexcing on tensor 

In [78]:
my_tensor[:,1:3]

tensor([[0.6827, 0.3909],
        [0.6682, 0.7992],
        [0.1723, 0.9610]], device='cuda:0')

#### Multiplication of tensors
- mul() function
- Using * symbol

In [79]:
my_tensor.mul(my_tensor)

tensor([[0.0131, 0.4661, 0.1528, 0.5909],
        [0.7413, 0.4465, 0.6387, 0.1226],
        [0.0795, 0.0297, 0.9235, 0.0204]], device='cuda:0')

In [80]:
my_tensor*my_tensor

tensor([[0.0131, 0.4661, 0.1528, 0.5909],
        [0.7413, 0.4465, 0.6387, 0.1226],
        [0.0795, 0.0297, 0.9235, 0.0204]], device='cuda:0')

#### Matrix multiplication

In [81]:
my_tensor.matmul(my_tensor.T)

tensor([[1.2229, 1.1363, 0.6354],
        [1.1363, 1.9491, 1.1760],
        [0.6354, 1.1760, 1.0532]], device='cuda:0')

#### Matrix multiplication using torch

In [82]:
torch.matmul(my_tensor,my_tensor.T)

tensor([[1.2229, 1.1363, 0.6354],
        [1.1363, 1.9491, 1.1760],
        [0.6354, 1.1760, 1.0532]], device='cuda:0')

#### Matrix multiplication 
- Using @ symbol

In [83]:
my_tensor@my_tensor.T

tensor([[1.2229, 1.1363, 0.6354],
        [1.1363, 1.9491, 1.1760],
        [0.6354, 1.1760, 1.0532]], device='cuda:0')

#### Summation of tensor

In [84]:
my_tensor.sum(axis=1)

tensor([1.9568, 2.6785, 1.5581], device='cuda:0')

#### Maximum and Minimum function

In [85]:
torch.max(my_tensor)

tensor(0.9610, device='cuda:0')

In [86]:
torch.min(my_tensor)

tensor(0.1145, device='cuda:0')

#### Concatination of tensors
- cat() function

In [87]:
torch.cat([my_tensor,my_tensor],dim=1)

tensor([[0.1145, 0.6827, 0.3909, 0.7687, 0.1145, 0.6827, 0.3909, 0.7687],
        [0.8610, 0.6682, 0.7992, 0.3501, 0.8610, 0.6682, 0.7992, 0.3501],
        [0.2820, 0.1723, 0.9610, 0.1428, 0.2820, 0.1723, 0.9610, 0.1428]],
       device='cuda:0')

#### Concatination using axis

In [88]:
torch.cat([my_tensor,my_tensor],axis=1)

tensor([[0.1145, 0.6827, 0.3909, 0.7687, 0.1145, 0.6827, 0.3909, 0.7687],
        [0.8610, 0.6682, 0.7992, 0.3501, 0.8610, 0.6682, 0.7992, 0.3501],
        [0.2820, 0.1723, 0.9610, 0.1428, 0.2820, 0.1723, 0.9610, 0.1428]],
       device='cuda:0')

#### Softmax function

In [89]:
torch.nn.functional.softmax(my_tensor,dim=1)

tensor([[0.1665, 0.2938, 0.2195, 0.3202],
        [0.2972, 0.2451, 0.2794, 0.1783],
        [0.2111, 0.1891, 0.4162, 0.1836]], device='cuda:0')

- Shape and Size

In [90]:
my_tensor.shape

torch.Size([3, 4])

In [91]:
my_tensor.size()

torch.Size([3, 4])

#### On image data
- if we are working on image data.
- 10 is the batch size
- 3 are the  number of channels
- 128,128 ia the image size

In [92]:
torch.rand(10,3,128,128)

tensor([[[[0.2859, 0.1855, 0.4491,  ..., 0.0427, 0.4722, 0.4714],
          [0.8715, 0.3297, 0.5384,  ..., 0.2540, 0.6599, 0.3112],
          [0.0024, 0.4924, 0.1481,  ..., 0.8874, 0.4576, 0.0802],
          ...,
          [0.3730, 0.6092, 0.1680,  ..., 0.4280, 0.0852, 0.5600],
          [0.9537, 0.0891, 0.4359,  ..., 0.7723, 0.7923, 0.4384],
          [0.3018, 0.2031, 0.0664,  ..., 0.4837, 0.7068, 0.0056]],

         [[0.5452, 0.9576, 0.9823,  ..., 0.7116, 0.6716, 0.7796],
          [0.8957, 0.7606, 0.5818,  ..., 0.3894, 0.7071, 0.9698],
          [0.4358, 0.9568, 0.6260,  ..., 0.6881, 0.5226, 0.1639],
          ...,
          [0.1988, 0.3897, 0.9187,  ..., 0.8355, 0.4043, 0.8135],
          [0.2886, 0.2787, 0.6188,  ..., 0.7378, 0.7563, 0.1563],
          [0.7220, 0.8055, 0.3477,  ..., 0.0027, 0.5983, 0.8316]],

         [[0.8162, 0.3499, 0.3069,  ..., 0.5695, 0.1427, 0.8866],
          [0.0645, 0.1824, 0.0670,  ..., 0.3150, 0.9921, 0.7869],
          [0.4681, 0.3747, 0.9601,  ..., 0

#### Check size
- size()

In [93]:
torch.rand(10,3,128,128).size()

torch.Size([10, 3, 128, 128])

In [94]:
my_tensor

tensor([[0.1145, 0.6827, 0.3909, 0.7687],
        [0.8610, 0.6682, 0.7992, 0.3501],
        [0.2820, 0.1723, 0.9610, 0.1428]], device='cuda:0')

#### Clip function
- minmum and maximum

In [95]:
my_tensor.clip(0.2,0.8)

tensor([[0.2000, 0.6827, 0.3909, 0.7687],
        [0.8000, 0.6682, 0.7992, 0.3501],
        [0.2820, 0.2000, 0.8000, 0.2000]], device='cuda:0')

#### Tensor to np.array 

In [96]:
my_tensor.cpu().detach().numpy()

array([[0.11448944, 0.68272716, 0.39088625, 0.7686735 ],
       [0.86097383, 0.6682273 , 0.79916936, 0.35013372],
       [0.28200096, 0.17234963, 0.96100706, 0.14278954]], dtype=float32)